/*
 * File: app/view/vitalsDetails.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientVitalsMonitoring.view.vitalsDetails', {
    extend: 'Ext.carousel.Carousel',
    alias: 'widget.vitalDetails',

    requires: [
        'Ext.carousel.Carousel',
        'Ext.form.Panel',
        'Ext.Label',
        'Ext.field.Select',
        'Ext.form.FieldSet',
        'Ext.field.Radio'
    ],

    config: {
        fullscreen: true,
        height: 522,
        items: [
            {
                xtype: 'carousel',
                styleHtmlContent: true,
                items: [
                    {
                        xtype: 'formpanel',
                        items: [
                            {
                                xtype: 'label',
                                height: 50,
                                html: 'Vital Signs',
                                style: 'font-weight:bold;font-size:24px',
                                styleHtmlContent: true
                            },
                            {
                                xtype: 'textfield',
                                width: 294,
                                label: 'O2 Sat :'
                            },
                            {
                                xtype: 'textfield',
                                width: 294,
                                label: 'Heart Rate :',
                                labelWidth: '50%'
                            },
                            {
                                xtype: 'textfield',
                                width: 294,
                                label: 'Blood Pressure :',
                                labelWidth: '55%'
                            },
                            {
                                xtype: 'textfield',
                                width: 292,
                                label: 'Weight (Kg/Lbs) :',
                                labelWidth: '50%'
                            }
                        ]
                    },
                    {
                        xtype: 'formpanel',
                        height: 537,
                        items: [
                            {
                                xtype: 'selectfield',
                                itemId: 'myselectfield',
                                label: 'Do you have shortness of Breath?',
                                labelWidth: '80%',
                                labelWrap: true,
                                options: [
                                    {
                                        text: 'Select',
                                        value: 'Select'
                                    },
                                    {
                                        text: 'Yes',
                                        value: 'Yes'
                                    },
                                    {
                                        text: 'No',
                                        value: 'No'
                                    }
                                ]
                            },
                            {
                                xtype: 'textfield',
                                disabled: false,
                                height: 69,
                                hidden: false,
                                id: 'txtSOBDuration',
                                style: 'display:none',
                                label: 'For how long ?',
                                labelWidth: '',
                                labelWrap: true
                            },
                            {
                                xtype: 'fieldset',
                                height: 88,
                                width: 285,
                                layout: 'hbox',
                                title: 'Have you had cough?',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        itemId: 'myradiobutton',
                                        width: '40%',
                                        label: 'Yes',
                                        labelAlign: 'right',
                                        labelWidth: '',
                                        name: 'rdCough'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        width: '40%',
                                        label: 'No',
                                        labelAlign: 'right',
                                        labelWidth: '',
                                        name: 'rdCough'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                height: 88,
                                id: 'fsProductive',
                                style: 'display:none',
                                width: 285,
                                layout: 'hbox',
                                title: 'Is it Productive ?',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        itemId: 'myradiobutton1',
                                        width: 139,
                                        label: 'Yes',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdProductive'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        width: 135,
                                        label: 'No',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdProductive'
                                    }
                                ]
                            },
                            {
                                xtype: 'selectfield',
                                id: 'selColor',
                                style: 'display:none',
                                width: 297,
                                label: 'Color ?',
                                options: [
                                    {
                                        text: 'Select',
                                        value: 'Select'
                                    },
                                    {
                                        text: 'Clear',
                                        value: 'Clear'
                                    },
                                    {
                                        text: 'Yellow',
                                        value: 'Yellow'
                                    },
                                    {
                                        text: 'Pink',
                                        value: 'Pink'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'formpanel',
                        height: 641,
                        scrollable: true,
                        items: [
                            {
                                xtype: 'fieldset',
                                height: 88,
                                layout: 'hbox',
                                title: 'Do you have swelling?',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        itemId: 'myradiobutton6',
                                        width: 144,
                                        label: 'Yes',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdSwelling'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        width: 146,
                                        label: 'No',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdSwelling'
                                    }
                                ]
                            },
                            {
                                xtype: 'textfield',
                                id: 'txtWhere',
                                style: 'display:none',
                                label: 'Where :'
                            },
                            {
                                xtype: 'selectfield',
                                id: 'selFrequency',
                                style: 'display:none',
                                label: 'Frequency :',
                                labelWidth: '40%',
                                options: [
                                    {
                                        text: 'Select',
                                        value: 'Select'
                                    },
                                    {
                                        text: 'Increased',
                                        value: 'Increased'
                                    },
                                    {
                                        text: 'Same',
                                        value: 'Same'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'formpanel',
                        items: [
                            {
                                xtype: 'fieldset',
                                width: 284,
                                layout: 'hbox',
                                title: 'Are you using oxygen ?',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        itemId: 'myradiobutton4',
                                        width: 127,
                                        label: 'Yes',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdOxygen'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        height: 43,
                                        width: 114,
                                        label: 'No',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdOxygen'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                id: 'fsOxygenNew',
                                style: 'display:none',
                                width: 284,
                                layout: 'hbox',
                                title: 'Is this new ?',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        width: 120,
                                        label: 'Yes',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdOxygenNew'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        width: 129,
                                        label: 'No',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdOxygenNew'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                id: 'fsOxygenHowMuch',
                                style: 'display:none',
                                width: 286,
                                layout: 'hbox',
                                title: 'How much ?',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'txtOxygen',
                                        label: ''
                                    },
                                    {
                                        xtype: 'label',
                                        centered: false,
                                        html: 'L/min'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                id: 'fsOxygenHelping',
                                style: 'display:none',
                                width: 282,
                                layout: 'hbox',
                                title: 'Is it helping ?',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        width: 121,
                                        label: 'Yes',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdOxygenHelping'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        width: 130,
                                        label: 'No',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdOxygenHelping'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'formpanel',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'fieldset',
                                id: 'fsDailyMedicine',
                                layout: 'hbox',
                                title: 'Have you taken your medicine daily?',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        width: 138,
                                        label: 'Yes',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdMedicineDaily'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        width: 150,
                                        label: 'No',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdMedicineDaily'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMyselectfieldChange',
                event: 'change',
                delegate: '#myselectfield'
            },
            {
                fn: 'onMyradiobuttonChange',
                event: 'change',
                delegate: '#myradiobutton'
            },
            {
                fn: 'onMyradiobutton1Change',
                event: 'change',
                delegate: '#myradiobutton1'
            },
            {
                fn: 'onMyradiobutton6Change',
                event: 'change',
                delegate: '#myradiobutton6'
            },
            {
                fn: 'onMyradiobutton4Change',
                event: 'change',
                delegate: '#myradiobutton4'
            }
        ]
    },

    onMyselectfieldChange: function(selectfield, newValue, oldValue, eOpts) {
                        if (newValue=='Yes') {
                            document.getElementById('txtSOBDuration').style.display='block';
                      } else {
                           document.getElementById('txtSOBDuration').style.display='none';
                      }

    },

    onMyradiobuttonChange: function(checkboxfield, newValue, oldValue, eOpts) {
               if(newValue) {
                   document.getElementById("fsProductive").style.display='block';
               } else {
                   document.getElementById("fsProductive").style.display='none';
                   document.getElementById("selColor").style.display='none';

               }
    },

    onMyradiobutton1Change: function(checkboxfield, newValue, oldValue, eOpts) {
                if (newValue) {
                    document.getElementById("selColor").style.display='block';
                } else {
                    document.getElementById("selColor").style.display='none';
                }
    },

    onMyradiobutton6Change: function(checkboxfield, newValue, oldValue, eOpts) {
                    if (newValue){
                        document.getElementById("txtWhere").style.display='block';
                        document.getElementById("selFrequency").style.display='block';
                    } else {
                        document.getElementById("txtWhere").style.display='none';
                        document.getElementById("selFrequency").style.display='none';
                    }
    },

    onMyradiobutton4Change: function(checkboxfield, newValue, oldValue, eOpts) {
                    if (newValue) {
                       document.getElementById("fsOxygenNew").style.display='block';
                       document.getElementById("fsOxygenHowMuch").style.display='block';
                       document.getElementById("fsOxygenHelping").style.display='block';
                    } else {
                       document.getElementById("fsOxygenNew").style.display='none';
                       document.getElementById("fsOxygenHowMuch").style.display='none';
                       document.getElementById("fsOxygenHelping").style.display='none';
                    }
    }

});