/*
 * File: app/view/vitalsDetails.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientVitalsMonitoring.view.vitalsDetails', {
    extend: 'Ext.carousel.Carousel',
    alias: 'widget.vitalDetails',

    requires: [
        'Ext.carousel.Carousel',
        'Ext.form.Panel',
        'Ext.field.Select',
        'Ext.form.FieldSet',
        'Ext.field.Radio'
    ],

    config: {
        items: [
            {
                xtype: 'carousel',
                items: [
                    {
                        xtype: 'formpanel',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Heart Rate'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Blood Pressue'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Weight'
                            }
                        ]
                    },
                    {
                        xtype: 'formpanel',
                        items: [
                            {
                                xtype: 'selectfield',
                                itemId: 'myselectfield',
                                label: 'Do you have shortness of Breath?',
                                options: [
                                    {
                                        text: 'Choose one',
                                        value: 'Choose one'
                                    },
                                    {
                                        text: 'Yes',
                                        value: 'Yes'
                                    },
                                    {
                                        text: 'No',
                                        value: 'No'
                                    }
                                ]
                            },
                            {
                                xtype: 'textfield',
                                disabled: false,
                                hidden: false,
                                id: 'txtSOBDuration',
                                style: 'display:none',
                                label: 'For how long ?'
                            },
                            {
                                xtype: 'fieldset',
                                width: '40%',
                                title: 'Have you had cough?',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        width: '40%',
                                        label: 'Yes',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdCough'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        width: '40%',
                                        label: 'No',
                                        labelAlign: 'right',
                                        labelWidth: '40%',
                                        name: 'rdCough'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                centered: false,
                                width: '40%',
                                title: 'Color',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        label: 'Clear',
                                        labelAlign: 'right',
                                        labelWrap: true,
                                        name: 'rdColor'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        label: 'Yellow',
                                        labelAlign: 'right',
                                        labelWrap: true,
                                        name: 'rdColor'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        label: 'Pink',
                                        labelAlign: 'right',
                                        labelWrap: true,
                                        name: 'rdColor'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'formpanel',
                        items: [
                            {
                                xtype: 'fieldset',
                                title: 'Do you have swelling?',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        label: 'Yes',
                                        name: 'rdSwelling'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        label: 'No',
                                        name: 'rdSwelling'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                title: 'Are you using Oxygen ?',
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        label: 'Yes',
                                        name: 'rdOxygen'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        label: 'No',
                                        name: 'rdOxygen'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                title: '',
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        title: 'Is this new ?',
                                        items: [
                                            {
                                                xtype: 'radiofield',
                                                label: 'Yes',
                                                name: 'rdOxygenNew'
                                            },
                                            {
                                                xtype: 'radiofield',
                                                label: 'No',
                                                name: 'rdOxygenNew'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: 'How much'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMyselectfieldChange',
                event: 'change',
                delegate: '#myselectfield'
            }
        ]
    },

    onMyselectfieldChange: function(selectfield, newValue, oldValue, eOpts) {
                        if (newValue=='Yes') {
                            document.getElementById('txtSOBDuration').style.display='block';
                      } else {
                           document.getElementById('txtSOBDuration').style.display='none';
                      }

    }

});